language: java
jdk:
  - openjdk8
install: true

script:
- git config --local user.name "Travis CI"
- git config --local user.email "builds@travis-ci.com"
- git checkout -f master
- mvn -B -s settings.xml release:prepare -DskipTests=true -DscmCommentPrefix="[ci skip][maven-release-plugin] " -Dusername=${GITHUB_USERNAME} -Dpassword=${GITHUB_TOKEN}
before_deploy:
- export TAG=$(git describe --tags --abbrev=0)
deploy:
  skip_cleanup: true
  provider: releases
  api_key: ${GITHUB_TOKEN}
  tag_name: $TAG
  file:
    - target/$TAG-boot.jar
    - target/$TAG-import.jar
  on:
    repo: Backbase/bb-fuel
  name: $TAG
branches:
  only:
  - master
