environment:
  domain: backbase.test:8080
  domain-identity: backbase.test:8180

bb-fuel:
  platform:
    registry: http://registry.${environment.name}.${environment.domain}
    identity: http://identity.${environment.name}.${environment.domain}
    gateway: http://edge.${environment.name}.${environment.domain}/api
    auth: http://edge.${environment.name}.${environment.domain}/api/auth/login
    tokenconverter: http://tokenconverter.${environment.name}.${environment.domain}
  dbs:
    accessgroup: http://${environment.name}.${environment.domain}/accessgroup
    accounts: http://${environment.name}.${environment.domain}/account/service-api
    approvals: http://${environment.name}.${environment.domain}/approvals/client-api
    arrangements: http://${environment.name}.${environment.domain}/arrangements/client-api
    billpay: http://${environment.name}.${environment.domain}/billpayprovidermock/client-api
    contactmanager: http://${environment.name}.${environment.domain}/contacts/client-api
    legalentity: http://${environment.name}.${environment.domain}/legalentity
    transactions: http://${environment.name}.${environment.domain}/transactions
    user: http://${environment.name}.${environment.domain}/user/client-api
    accountStatement: http://${environment.name}.${environment.domain}/accountstatementsintegration/account-statement-integration-service/service-api
  dbs-service-names:
    accessgroup: accessgroup-presentation-service
    actions: actionrecipes-presentation-service
    arrangements: product-summary-presentation-service
    billpay: billpay-presentation-service
    legalentity: legalentity-presentation-service
    limits: limits-presentation-service
    messages: messages-presentation-service
    notifications: notifications-presentation-service
    payments: payment-order-presentation-service
    pfm: categories-management-presentation-service
    user: user-presentation-service
    products: product-summary-presentation-service
