environment:
  domain: backbase.test

bb-fuel:
  platform:
    registry: http://registry.${environment.name}.${environment.domain}
    identity: http://identity.${environment.name}.${environment.domain}
    gateway: http://edge.${environment.name}.${environment.domain}/api
    auth: http://edge.${environment.name}.${environment.domain}/api/auth/login
    tokenconverter: http://tokenconverter.${environment.name}.${environment.domain}
  dbs:
    accessgroup: http://accessgroup.${environment.name}.${environment.domain}
    accounts: http://account.${environment.name}.${environment.domain}/service-api
    approvals: http://approvals.${environment.name}.${environment.domain}/integration-api
    arrangements: http://arrangement.${environment.name}.${environment.domain}/integration-api
    billpay: http://billpayprovidermock.${environment.name}.${environment.domain}/client-api
    contactmanager: http://contacts.${environment.name}.${environment.domain}/integration-api
    legalentity: http://legalentity.${environment.name}.${environment.domain}
    transactions: http://transactions.${environment.name}.${environment.domain}/integration-api
    user: http://user-manager.${environment.name}.${environment.domain}/integration-api
    accountStatement: http://accountstatementsintegration.${environment.name}.${environment.domain}/service-api
    pockets: http://edge.${environment.name}.${environment.domain}/api/pocket-tailor/client-api
    pocketsArrangements: http://arrangementoutboundoriginationmock.${environment.name}.${environment.domain}/service-api
    contentservices: http://edge.${environment.name}.${environment.domain}/api/contentservices/client-api
    userProfileManager: http://edge.${environment.name}.${environment.domain}:80/api
  dbs-service-names:
    accessgroup: access-control
    actions: action
    arrangements: arrangements-manager
    billpay: billpay-integrator
    legalentity: access-control
    limits: limit
    messages: messages-service
    notifications: notifications-service
    payments: payment-order-service
    pfm: transaction-category-collector
    user: user-manager
    products: arrangement-manager
    positivePay: positive-pay-check
    contentservices: contentservices
    userprofilemanager: user-profile-manager
