environment:
  domain: backbase.test

bb-fuel:
  platform:
    registry: http://registry.${environment.name}.${environment.domain}
    identity: http://identity.${environment.name}.${environment.domain}
    gateway: http://edge.${environment.name}.${environment.domain}/api
    auth: http://edge.${environment.name}.${environment.domain}/api/auth/login
    tokenconverter: http://tokenconverter.${environment.name}.${environment.domain}
  dbs:
    approvals: http://approvals.${environment.name}.${environment.domain}/client-api
    transactions: http://transactions.${environment.name}.${environment.domain}
    contactmanager: http://contacts.${environment.name}.${environment.domain}/client-api
    messages: http://messagecenter.${environment.name}.${environment.domain}/client-api
    user: http://user.${environment.name}.${environment.domain}
    legalentity: http://legalentity.${environment.name}.${environment.domain}
    accessgroup: http://accessgroup.${environment.name}.${environment.domain}
    arrangements: http://arrangements.${environment.name}.${environment.domain}
    billpay: http://billpayprovidermock.${environment.name}.${environment.domain}
    accounts: http://account.${environment.name}.${environment.domain}
  dbs-service-names:
    accessgroup: accessgroup-presentation-service
    actions: actionrecipes-presentation-service
    arrangements: product-summary-presentation-service
    billpay: billpay-presentation-service
    legalentity: legalentity-presentation-service
    limits: limits-presentation-service
    messages: messages-presentation-service
    notifications: notifications-presentation-service
    payments: payment-order-presentation-service
    pfm: categories-management-presentation-service
    user: user-presentation-service
    products: product-summary-presentation-service