spring:
  application:
    name: bb-fuel
    version: @project.version@

logging:
  secured:
    enabled: false
  level:
    com.backbase: WARN
    org.springframework: WARN
    com.backbase.ct.bbfuel: DEBUG

sso.jwt.internal.signature.key:
  type: ENV
  value: SIG_SECRET_KEY

security.basic.enabled: false

eureka.client.enabled: false


environment:
  name: 13.f5
  domain: backbase.test

bb-fuel:
  platform:
    infra: http://edge.${environment.name}.${environment.domain}
    registry: registry.${environment.name}.${environment.domain}
    gateway: ${bb-fuel.platform.infra}/api
    auth: ${bb-fuel.platform.gateway}/auth/login
    tokenconverter: tokenconverter.${environment.name}.${environment.domain}
  dbs:
    approvals: http://approvals.${environment.name}.${environment.domain}/approval-integration-service
    transactions: http://transactions.${environment.name}.${environment.domain}/transaction-integration-service
    contactmanager: http://contacts.${environment.name}.${environment.domain}/contact-integration-service
    messages: http://messages.${environment.name}.${environment.domain}/messages-integration-service
    user: http://user.${environment.name}.${environment.domain}/user-integration-service
    legalentity: http://legalentity.${environment.name}.${environment.domain}/legalentity-integration-service
    accessgroup: http://accessgroup.${environment.name}.${environment.domain}/accessgroup-integration-service
    arrangements: http://arrangements.${environment.name}.${environment.domain}/arrangements-integration-service
    notifications: http://notifications.${environment.name}.${environment.domain}/notifications-presentation-service

backbase:
  activemq:
    enabled: false
  communication:
    outbound: HTTP
    inbound: HTTP
