spring:
  application:
    name: bb-fuel
    version: @project.version@

logging:
  secured:
    enabled: false
  level:
    com.backbase: WARN
    org.springframework: WARN
    com.backbase.ct.bbfuel: DEBUG

sso.jwt.internal.signature.key:
  type: ENV
  value: SIG_SECRET_KEY

security.basic.enabled: false

eureka.client.enabled: false

environment:
  domain: backbase.test:8080

bb-fuel:
  platform:
    infra: http://${environment.name}-${infra.base:infra}.${environment.domain}
    registry: ${bb-fuel.platform.infra}/registry/eureka
    gateway: ${bb-fuel.platform.infra}/gateway/api
    auth: ${bb-fuel.platform.gateway}/auth/login
    tokenconverter: ${bb-fuel.platform.infra}/bb-authentication-token-converter-service
  dbs:
    approvals: http://${environment.name}-approvals.${environment.domain}/approval-integration-service
    transactions: http://${environment.name}-transactions.${environment.domain}/transaction-integration-service
    contactmanager: http://${environment.name}-contactmanager.${environment.domain}/contact-integration-service
    messages: http://${environment.name}-messages.${environment.domain}/messages-integration-service
    user: http://${environment.name}-entitlements.${environment.domain}/user-integration-service
    legalentity: http://${environment.name}-entitlements.${environment.domain}/legalentity-integration-service
    accessgroup: http://${environment.name}-entitlements.${environment.domain}/accessgroup-integration-service
    arrangements: http://${environment.name}-productsummary.${environment.domain}/arrangements-integration-service
    notifications: http://${environment.name}-notifications.${environment.domain}/notifications-presentation-service

backbase:
  activemq:
    enabled: false
  communication:
    outbound: HTTP
    inbound: HTTP
