environment:
  domain: backbase.test:8080
  domain-identity: backbase.test:8180

bb-fuel:
  platform:
    registry: https://registry.${environment.name}.${environment.domain}
    identity: https://identity.${environment.name}.${environment.domain}
    gateway: https://edge.${environment.name}.${environment.domain}/api
    auth: https://edge.${environment.name}.${environment.domain}/api/auth/login
    tokenconverter: https://tokenconverter.${environment.name}.${environment.domain}
  dbs:
    accessgroup: https://${environment.name}.${environment.domain}/accessgroup
    accounts: https://${environment.name}.${environment.domain}/account/service-api
    approvals: https://${environment.name}.${environment.domain}/approvals/integration-api
    arrangements: https://${environment.name}.${environment.domain}/arrangements/integration-api
    billpay: https://${environment.name}.${environment.domain}/billpayprovidermock/client-api
    contactmanager: https://${environment.name}.${environment.domain}/contacts/integration-api
    legalentity: https://${environment.name}.${environment.domain}/legalentity
    transactions: https://${environment.name}.${environment.domain}/transactions/integration-api
    user: https://${environment.name}.${environment.domain}/user-manager/integration-api
    accountStatement: https://${environment.name}.${environment.domain}/accountstatementsintegration/account-statement-integration-service/service-api
  dbs-service-names:
    accessgroup: accessgroup-presentation-service
    actions: actionrecipes-presentation-service
    arrangements: product-summary-presentation-service
    billpay: billpay-presentation-service
    legalentity: legalentity-presentation-service
    limits: limits-presentation-service
    messages: messages-presentation-service
    notifications: notifications-presentation-service
    payments: payment-order-presentation-service
    pfm: categories-management-presentation-service
    user: user-presentation-service
    products: product-summary-presentation-service
