bb-fuel:
  platform:
    registry: https://registry.${environment.name}.${environment.domain}
    identity: https://identity.${environment.name}.${environment.domain}
    gateway: https://app.${environment.name}.${environment.domain}/api
    auth: https://app.${environment.name}.${environment.domain}/api/auth/login
    tokenconverter: https://app.${environment.name}.${environment.domain}/tokenconverter
  dbs:
    accessgroup: https://app.${environment.name}.${environment.domain}/accessgroup
    accounts: https://app.${environment.name}.${environment.domain}/account/service-api
    approvals: https://app.${environment.name}.${environment.domain}/approvals/integration-api
    arrangements: https://app.${environment.name}.${environment.domain}/arrangement/integration-api
    billpay: https://app.${environment.name}.${environment.domain}/billpayprovidermock/client-api
    contactmanager: https://app.${environment.name}.${environment.domain}/contacts/integration-api
    legalentity: https://app.${environment.name}.${environment.domain}/legalentity
    transactions: https://app.${environment.name}.${environment.domain}/transactions/integration-api
    user: https://app.${environment.name}.${environment.domain}/user-manager/integration-api
    accountStatement: https://app.${environment.name}.${environment.domain}/accountstatementsintegration/service-api
#    TODO TRANS-5724 look up correct configs
    pockets: http://app.${environment.name}.${environment.domain}/api/pocket-tailor/client-api
    pocketsArrangements: http://app.${environment.name}.${environment.domain}/arrangementoutboundoriginationmock/service-api
  dbs-service-names:
    accessgroup: access-control
    actions: action
    arrangements: arrangements-manager
    billpay: billpay-integrator
    legalentity: access-control
    limits: limit
    messages: messages-service
    notifications: notifications-service
    payments: payment-order-service
    pfm: transaction-category-collector
    user: user-manager
    products: arrangement-manager