spring:
  application:
    name: bb-fuel
    version: @project.version@
#  activemq:
#    broker-url: ${activemq.url:tcp://${environment.name}-infra.backbase.test:51616}

logging:
  secured:
    enabled: false
  level:
    com.backbase: WARN
    org.springframework: WARN
    com.backbase.ct.bbfuel: DEBUG

sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

security:
  basic:
    enabled: false

eureka:
  client:
    enabled: false
