bb-fuel:
  platform:
    infra: http://localhost:8080
    identity: http://localhost:8180
    registry: ${bb-fuel.platform.infra}/registry/eureka
    gateway: ${bb-fuel.platform.infra}/gateway/api
    auth: ${bb-fuel.platform.gateway}/auth/login
    tokenconverter: ${bb-fuel.platform.infra}/bb-authentication-token-converter-service
  dbs:
    approvals: http://localhost:8090/approval-integration-service
    transactions: http://localhost:8083/transaction-integration-service
    contactmanager: http://localhost:8081/contact-integration-service
    messages: http://localhost:8084/messages-integration-service
    user: http://localhost:8086/user-integration-service
    legalentity: http://localhost:8086/legalentity-integration-service
    accessgroup: http://localhost:8086/accessgroup-integration-service
    arrangements: http://localhost:8082/arrangements-integration-service
    notifications: http://localhost:8082/notifications-presentation-service