environment:
  domain: backbase.test:8080
  domain-identity: backbase.test:8180

bb-fuel:
  platform:
    infra: http://${environment.name}-${infra.base:infra}.${environment.domain}
    identity: http://${environment.name}-bbiam.${environment.domain-identity}
    registry: ${bb-fuel.platform.infra}/registry/eureka
    gateway: ${bb-fuel.platform.infra}/gateway/api
    auth: ${bb-fuel.platform.gateway}/auth/login
    tokenconverter: ${bb-fuel.platform.infra}/bb-authentication-token-converter-service
  dbs:
    approvals: http://${environment.name}-approvals.${environment.domain}/approval-integration-service/client-api
    transactions: http://${environment.name}-transactions.${environment.domain}/transaction-integration-service
    contactmanager: http://${environment.name}-contactmanager.${environment.domain}/contact-integration-service/client-api
    messages: http://${environment.name}-messages.${environment.domain}/messages-integration-service
    user: http://${environment.name}-entitlements.${environment.domain}/user-integration-service
    legalentity: http://${environment.name}-entitlements.${environment.domain}/legalentity-integration-service
    accessgroup: http://${environment.name}-entitlements.${environment.domain}/accessgroup-integration-service
    arrangements: http://${environment.name}-productsummary.${environment.domain}/arrangements-integration-service
    billpay: http://${environment.name}-billpay.${environment.domain}/billpay-mockbank
    accounts: http://${environment.name}-productsummary.${environment.domain}/account-integration-service
  dbs-service-names:
    accessgroup: accessgroup-presentation-service
    actions: actionrecipes-presentation-service
    arrangements: product-summary-presentation-service
    billpay: billpay-presentation-service
    legalentity: legalentity-presentation-service
    limits: limits-presentation-service
    messages: messages-presentation-service
    notifications: notifications-presentation-service
    payments: payment-order-presentation-service
    pfm: categories-management-presentation-service
    user: user-presentation-service
    products: product-summary-presentation-service
