environment:
  domain: backbase.test

bb-fuel:
  platform:
    registry: http://registry.${environment.name}.${environment.domain}
    identity: http://bbiam.${environment.name}.${environment.domain}
    gateway: http://edge.${environment.name}.${environment.domain}/api
    auth: http://edge.${environment.name}.${environment.domain}/api/auth/login
    tokenconverter: http://tokenconverter.${environment.name}.${environment.domain}
  dbs:
    approvals: http://approvals.${environment.name}.${environment.domain}
    transactions: http://transactions.${environment.name}.${environment.domain}
    contactmanager: http://contacts.${environment.name}.${environment.domain}
    messages: http://messages.${environment.name}.${environment.domain}
    user: http://user.${environment.name}.${environment.domain}
    legalentity: http://legalentity.${environment.name}.${environment.domain}
    accessgroup: http://accessgroup.${environment.name}.${environment.domain}
    arrangements: http://arrangements.${environment.name}.${environment.domain}
    notifications: http://notifications.${environment.name}.${environment.domain}
