spring:
  application:
    name: bb-fuel
    version: @project.version@

logging:
  secured:
    enabled: false
  level:
    com.backbase: WARN
    org.springframework: WARN
    com.backbase.ct.bbfuel: DEBUG

sso.jwt.internal.signature.key:
  type: ENV
  value: SIG_SECRET_KEY

security.basic.enabled: false

eureka.client.enabled: false


environment:
  name: 81.f5
  domain: backbase.test

bb-fuel:
  platform:
    infra: http://edge.${environment.name}.${environment.domain}
    registry: http://registry.${environment.name}.${environment.domain}
    gateway: http://${bb-fuel.platform.infra}/api
    auth: http://${bb-fuel.platform.gateway}/auth/login
    tokenconverter: http://tokenconverter.${environment.name}.${environment.domain}
  dbs:
    approvals: http://approvals.${environment.name}.${environment.domain}
    transactions: http://transactions.${environment.name}.${environment.domain}
    contactmanager: http://contactmanager.${environment.name}.${environment.domain}
    messages: http://messages.${environment.name}.${environment.domain}
    user: http://user.${environment.name}.${environment.domain}
    legalentity: http://legalentity.${environment.name}.${environment.domain}
    accessgroup: http://accessgroup.${environment.name}.${environment.domain}
    arrangements: http://arrangements.${environment.name}.${environment.domain}
    notifications: http://notifications.${environment.name}.${environment.domain}

backbase:
  activemq:
    enabled: false
  communication:
    outbound: HTTP
    inbound: HTTP
