environment:
  domain: eph.rnddb.azure.backbaseservices.com

bb-fuel:
  platform:
    registry: https://registry-${environment.name}.${environment.domain}
    identity: https://identity-${environment.name}.${environment.domain}
    gateway: https://app-${environment.name}.${environment.domain}/api
    auth: https://app-${environment.name}.${environment.domain}/api/auth/login
    tokenconverter: https://token-converter-${environment.name}.${environment.domain}
  dbs:
    accessgroup: https://accessgroup-integration-service-${environment.name}.${environment.domain}/integration-api
    accounts: https://account-integration-service-${environment.name}.${environment.domain}/service-api
    approvals: https://approval-service-${environment.name}.${environment.domain}/integration-api
    arrangements: https://arrangement-manager-${environment.name}.${environment.domain}/integration-api
    billpay: https://billpayprovidermock-${environment.name}.${environment.domain}/client-api
    contactmanager: https://contact-manager-${environment.name}.${environment.domain}/integration-api
    legalentity: https://legalentity-integration-service-${environment.name}.${environment.domain}/integration-api
    transactions: https://transaction-manager-${environment.name}.${environment.domain}/integration-api
    user: https://user-manager-${environment.name}.${environment.domain}/integration-api
    usermock: https://userintegrationexternalmock-${environment.name}.${environment.domain}/service-api
    accountStatement: https://account-statement-integration-service-${environment.name}.${environment.domain}/service-api
    pockets: https://app.${environment.name}-${environment.domain}/api/pocket-tailor/client-api
    pocketsArrangements: https://arrangementoutboundoriginationmock-${environment.name}.${environment.domain}/service-api
    contentservices: https://app.${environment.name}.${environment.domain}/api/contentservices/client-api
    userProfileManager: http://app.${environment.name}.${environment.domain}:80/api
  dbs-service-names:
    accessgroup: access-control
    actions: action
    arrangements: arrangements-manager
    billpay: billpay-integrator
    legalentity: access-control
    limits: limit
    messages: messages-service
    notifications: notifications-service
    payments: payment-order-service
    pfm: transaction-category-collector
    user: user-manager
    products: arrangement-manager
    positivePay: positive-pay-check
    contentservices: contentservices
    userprofilemanager: user-profile-manager
