name: GitHub Release Manual

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven
          restore-keys: |
            ${{ runner.os }}-maven
      - name: Build project
        env:
          REPO_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          REPO_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: mvn -B -s settings.xml package
      - name: Run GitHub release
        uses: ncipollo/release-action@v1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          artifacts: "target/bb-fuel-*-boot.jar,target/bb-fuel-*-import.jar"
          makeLatest: true
          tag: ${{ inputs.tag }}