name: Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      - name: Run maven release
        uses: qcastel/github-actions-maven-release@v1.12.31
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
          REPO_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          REPO_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        with:
          maven-servers: '[{"id":"Backbase Artifactory Repository","username":"${REPO_USERNAME}","password":"${REPO_PASSWORD}"}]'
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@backbase.com"
          release-branch-name: "master"
          skip-perform: true


