name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Run Maven release
        uses: qcastel/github-actions-maven-release@v1.12.31
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          maven-servers: '[{"id":"Public Backbase Repository","username":"${REPO_USERNAME}","password":"${REPO_PASSWORD}"}]'
          release-branch-name: "master"
          skip-perform: true
      - name: Get most recent tag
        id: most-recent-tag
        run: echo "tag=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT
      - name: Run GitHub release
        uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          artifacts: "target/bb-fuel-*-boot.jar,target/bb-fuel-*-import.jar"
          makeLatest: true
          tag: ${{ steps.most-recent-tag.outputs.tag }}
